#!/usr/bin/with-contenv bash

PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" git
usermod -o -u "$PUID" git

echo "
-------------------------------------
User uid:    $(id -u git)
User gid:    $(id -g git)
-------------------------------------
"
chown git:git /data
