version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-gomod:
        patterns: [ "*" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-devcontainers:
        patterns: [ "*" ]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: [ "*" ]
