docs-update-needed:
  - changed-files:
      - any-glob-to-any-file:
          - "custom/conf/app.example.ini"

topic/code-linting:
  - changed-files:
      - any-glob-to-any-file:
          - ".golangci.yml"
          - ".markdownlint.yaml"
          - ".spectral.yaml"
          - ".yamllint.yaml"
          - "eslint*.config.*"
          - "stylelint.config.*"
