rules:
  anonymous-definition:
    disable: true
  undocumented-permissions:
    disable: true
  concurrency-limits:
    disable: true
  self-repository:
    disable: true # actionlint rejects "$/" uses, https://github.com/rhysd/actionlint/issues/711
