// This file is generated by modules/charset/invisible/generate.go DO NOT EDIT
// Copyright 2022 The Gitea Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package charset

import "unicode"

var InvisibleRanges = &unicode.RangeTable{
	R16: []unicode.Range16{
		{Lo: 11, Hi: 13, Stride: 1},
		{Lo: 127, Hi: 160, Stride: 33},
		{Lo: 173, Hi: 847, Stride: 674},
		{Lo: 1564, Hi: 4447, Stride: 2883},
		{Lo: 4448, Hi: 6068, Stride: 1620},
		{Lo: 6069, Hi: 6155, Stride: 86},
		{Lo: 6156, Hi: 6158, Stride: 1},
		{Lo: 7355, Hi: 7356, Stride: 1},
		{Lo: 8192, Hi: 8207, Stride: 1},
		{Lo: 8234, Hi: 8239, Stride: 1},
		{Lo: 8287, Hi: 8303, Stride: 1},
		{Lo: 10240, Hi: 12288, Stride: 2048},
		{Lo: 12644, Hi: 65024, Stride: 52380},
		{Lo: 65025, Hi: 65039, Stride: 1},
		{Lo: 65279, Hi: 65440, Stride: 161},
		{Lo: 65520, Hi: 65528, Stride: 1},
		{Lo: 65532, Hi: 65532, Stride: 1},
	},
	R32: []unicode.Range32{
		{Lo: 78844, Hi: 119155, Stride: 40311},
		{Lo: 119156, Hi: 119162, Stride: 1},
		{Lo: 917504, Hi: 917631, Stride: 1},
		{Lo: 917760, Hi: 917999, Stride: 1},
	},
	LatinOffset: 2,
}
