FROM golang:1.17-alpine3.15

ARG GOPROXY
ENV GOPROXY ${GOPROXY:-direct}

ARG TAGS="sqlite sqlite_unlock_notify"
ENV TAGS "bindata timetzdata $TAGS"
ARG CGO_EXTRA_CFLAGS

#Build & runtime deps
RUN apk --no-cache add \
    build-base \
    git \
    nodejs \
    npm \
    bash \
    ca-certificates \
    curl \
    gettext \
    git \
    linux-pam \
    openssh \
    s6 \
    sqlite \
    su-exec \
    gnupg


#Setup repo
COPY . /go/src/code.gitea.io/gitea
WORKDIR /go/src/code.gitea.io/gitea

RUN npm install --no-save
RUN make build

# Begin env-to-ini build
RUN go build contrib/environment-to-ini/environment-to-ini.go

EXPOSE 22 3000

RUN addgroup \
    -S -g 1000 \
    git && \
    adduser \
    -S -H -D \
    -h /data/git \
    -s /bin/bash \
    -u 1000 \
    -G git \
    git && \
    echo "git:*" | chpasswd -e

ENV USER git
ENV GITEA_CUSTOM /data/gitea

VOLUME ["/data"]

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

COPY docker/root /
RUN mkdir -p /app/gitea
RUN cp /go/src/code.gitea.io/gitea/gitea /app/gitea/gitea
RUN cp /go/src/code.gitea.io/gitea/environment-to-ini /usr/local/bin/environment-to-ini
RUN chmod 755 /usr/bin/entrypoint /app/gitea/gitea /usr/local/bin/gitea /usr/local/bin/environment-to-ini
RUN chmod 755 /etc/s6/gitea/* /etc/s6/openssh/* /etc/s6/.s6-svscan/*
