savePrefix: ''
updateNotifier: false
ignoreScripts: true
minimumReleaseAge: 0
confirmModulesPurge: false
verifyDepsBeforeRun: false
allowBuilds:
  esbuild: set this to true or false
  unrs-resolver: set this to true or false
