#!/bin/bash

if [ ! -d /data/git/.ssh ]; then
    mkdir -p /data/git/.ssh
    chmod 700 /data/git/.ssh
fi

if [ ! -f /data/git/.ssh/environment ]; then
    echo "GITEA_CUSTOM=${GITEA_CUSTOM}" >| /data/git/.ssh/environment
    chmod 600 /data/git/.ssh/environment
fi

if [ ! -f "${GITEA_CUSTOM}/conf/app.ini" ]; then
    mkdir -p "${GITEA_CUSTOM}/conf"

    # Set INSTALL_LOCK to true only if SECRET_KEY is not empty and
    # INSTALL_LOCK is empty
    if [ -n "$SECRET_KEY" ] && [ -z "$INSTALL_LOCK" ]; then
        INSTALL_LOCK=true
    fi

    # Substitude the environment variables in the template
    envsubst < /etc/templates/app.ini > "${GITEA_CUSTOM}/conf/app.ini"
fi

# only chown if current owner is not already the gitea ${USER}. No recursive check to save time
if ! [[ $(ls -ld "${GITEA_CUSTOM}" | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git "${GITEA_CUSTOM}"; fi
if ! [[ $(ls -ld "${DATA_PATH}" | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git "${DATA_PATH}"; fi
if ! [[ $(ls -ld "${RUN_DIR}"  | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git "${RUN_DIR}";  fi
if ! [[ $(ls -ld /data/git   | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git /data/git;   fi
chmod 0755 "${GITEA_CUSTOM}" "${DATA_PATH}" "${RUN_DIR}" /data/git
