name: PR Compliance
on:
  push:
    branches: ["ci/**"]
jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - run: make deps-backend deps-tools
      - name: lint-go
        run: make lint-go
        env:
          TAGS: bindata sqlite sqlite_unlock_notify
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: make deps-frontend
      - name: lint-js
        run: make lint-js
      - name: lint-css
        run: make lint-css
      - name: test-frontend
        run: make test-frontend
