name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'spark_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      +table_format: iceberg
      materialized: table
      staging:
        materialized: view
