name: api feature Request
description: Got an idea for an api that Gitea doesn't have currently?  Submit your idea here!
labels: ["kind/api", "kind/feature", "kind/proposal"]
body:
- type: markdown
  attributes:
    value: |
      1. Please speak English, this is the language all maintainers can speak and write.
      2. Please ask questions or configuration/deploy problems on our Discord
         server (https://discord.gg/gitea) or forum (https://discourse.gitea.io).
      3. Please take a moment to check that your feature hasn't already been suggested.
- type: dropdown
  id: github-exist
  attributes:
    label: whether github has similar api?
    description: |
      If so, please provide a URL in the Description field.
      github api document: https://docs.github.com/en/rest
    options:
    - "Yes"
    - "No"
- type: textarea
  id: description
  attributes:
    label: api Feature Description
    placeholder: |
      I think it would be great if Gitea had...
  validations:
    required: true
