name: Feature Request
description: Suggest an idea for Gitea.
labels: ["type/proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Search [existing issues](https://github.com/go-gitea/gitea/issues?q=is%3Aissue) first.
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What do you propose?
    validations:
      required: true
