name: Feature Request
description: Got an idea for a feature that Gitea doesn't have currently?  Submit your idea here!
body:
- type: textarea
  id: description
  attributes:
    label: Feature Description
    placeholder: |
      I think it would be great if Gitea had...
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If you can, provide screenshots of an implementation on another site e.g. GitHub
