// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

package integration

import (
	"archive/zip"
	"bytes"
	"net/http"
	"net/url"
	"strings"
	"testing"

	actions_model "gitea.dev/models/actions"
	repo_model "gitea.dev/models/repo"
	"gitea.dev/models/unittest"
	"gitea.dev/modules/setting"
	"gitea.dev/modules/storage"
	"gitea.dev/modules/test"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func buildArtifactZip(t *testing.T, files map[string]string) []byte {
	t.Helper()
	var buf bytes.Buffer
	w := zip.NewWriter(&buf)
	for name, content := range files {
		fw, err := w.Create(name)
		require.NoError(t, err)
		_, err = fw.Write([]byte(content))
		require.NoError(t, err)
	}
	require.NoError(t, w.Close())
	return buf.Bytes()
}

func overwriteArtifactStorageContent(t *testing.T, artifactID int64, content []byte) {
	t.Helper()
	artifact := unittest.AssertExistsAndLoadBean(t, &actions_model.ActionArtifact{ID: artifactID})
	_, err := storage.ActionsArtifacts.Save(artifact.StoragePath, bytes.NewReader(content), int64(len(content)))
	require.NoError(t, err)
}

func TestActionsArtifactPreview(t *testing.T) {
	defer prepareTestEnvActionsArtifacts(t)()

	repo := unittest.AssertExistsAndLoadBean(t, &repo_model.Repository{ID: 4})
	session := loginUser(t, "user2")

	t.Run("RequiresSignIn", func(t *testing.T) {
		for _, path := range []string{
			"preview",
			"preview/raw",
			"preview/raw/abc.txt",
		} {
			req := NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/%s", repo.FullName(), path)
			resp := MakeRequest(t, req, http.StatusSeeOther)
			assert.Contains(t, resp.Header().Get("Location"), "/user/login")
		}
	})

	t.Run("SingleFile", func(t *testing.T) {
		req := NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/preview", repo.FullName())
		resp := session.MakeRequest(t, req, http.StatusOK)
		assert.Contains(t, resp.Body.String(), "abc.txt")
		assert.Contains(t, resp.Body.String(), "Back to action run #187")
		assert.Contains(t, resp.Body.String(), `href="/user5/repo4/actions/runs/791"`)
		assert.Contains(t, resp.Body.String(), `/preview?path=abc.txt" title="abc.txt"`)
		assert.NotContains(t, resp.Body.String(), "<iframe")

		req = NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/preview?path=abc.txt", repo.FullName())
		resp = session.MakeRequest(t, req, http.StatusOK)
		assert.Contains(t, resp.Body.String(), "This content was automatically generated by Gitea Actions.")
		assert.Contains(t, resp.Body.String(), `<iframe`)
		assert.Contains(t, resp.Body.String(), `/preview/raw/abc.txt`)
		assert.Contains(t, resp.Body.String(), `sandbox="allow-scripts"`)

		req = NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/preview/raw", repo.FullName())
		resp = session.MakeRequest(t, req, http.StatusOK)
		assert.Equal(t, strings.Repeat("A", 1024), resp.Body.String())
		assert.Contains(t, resp.Header().Get("Content-Type"), "text/plain")
	})

	t.Run("MultiFile", func(t *testing.T) {
		req := NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/multi-file-download/preview", repo.FullName())
		resp := session.MakeRequest(t, req, http.StatusOK)
		assert.Contains(t, resp.Body.String(), "abc.txt")
		assert.Contains(t, resp.Body.String(), "xyz/def.txt")

		req = NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/multi-file-download/preview?path=%s", repo.FullName(), url.QueryEscape("xyz/def.txt"))
		resp = session.MakeRequest(t, req, http.StatusOK)
		assert.Contains(t, resp.Body.String(), `/preview?path=xyz%2Fdef.txt" title="xyz/def.txt"`)

		req = NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/multi-file-download/preview/raw/xyz/def.txt", repo.FullName())
		resp = session.MakeRequest(t, req, http.StatusOK)
		assert.Equal(t, strings.Repeat("C", 1024), resp.Body.String())
	})

	t.Run("PathTraversal", func(t *testing.T) {
		// A traversal-style path normalizes to a path that doesn't match any file in
		// the artifact. The page still renders with the file list, but no preview is selected.
		req := NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/multi-file-download/preview?path=%s", repo.FullName(), url.QueryEscape("../../../etc/passwd"))
		resp := session.MakeRequest(t, req, http.StatusOK)
		assert.Contains(t, resp.Body.String(), "abc.txt")
		assert.NotContains(t, resp.Body.String(), "etc/passwd")
		// The artifact browser is still rendered, but no embedded preview is used.
		assert.NotContains(t, resp.Body.String(), "<iframe")

		// URL-encoded so the router doesn't collapse the segments before the handler sees them.
		req = NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/multi-file-download/preview/raw/%s", repo.FullName(), "%2E%2E%2F%2E%2E%2Fetc%2Fpasswd")
		session.MakeRequest(t, req, http.StatusNotFound)
	})

	t.Run("UnsupportedType", func(t *testing.T) {
		overwriteArtifactStorageContent(t, 1, []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n', 0x00, 0x00, 0x00, 0x0d})
		req := NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/preview/raw", repo.FullName())
		session.MakeRequest(t, req, http.StatusUnsupportedMediaType)
	})

	t.Run("HTMLSandboxCSP", func(t *testing.T) {
		overwriteArtifactStorageContent(t, 1, []byte("<html><body><h1>artifact</h1></body></html>"))
		req := NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/preview/raw", repo.FullName())
		resp := session.MakeRequest(t, req, http.StatusOK)
		assert.Equal(t, "sandbox allow-scripts", resp.Header().Get("Content-Security-Policy"))
		assert.Contains(t, resp.Header().Get("Content-Type"), "text/html")
	})

	t.Run("ArtifactTooLarge", func(t *testing.T) {
		oldMaxSize := setting.Actions.ArtifactPreviewMaxSize
		defer func() {
			setting.Actions.ArtifactPreviewMaxSize = oldMaxSize
		}()
		setting.Actions.ArtifactPreviewMaxSize = 1

		req := NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/preview", repo.FullName())
		resp := session.MakeRequest(t, req, http.StatusOK)
		assert.Contains(t, resp.Body.String(), "This artifact is too large to preview")
		assert.NotContains(t, resp.Body.String(), "/preview/raw/abc.txt")

		req = NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/preview/raw/abc.txt", repo.FullName())
		session.MakeRequest(t, req, http.StatusRequestEntityTooLarge)

		// no file list was computed, so the page must not also claim the requested file is missing
		req = NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/preview?path=abc.txt", repo.FullName())
		resp = session.MakeRequest(t, req, http.StatusOK)
		assert.NotContains(t, resp.Body.String(), "The requested file is not present")
	})

	t.Run("FileTooLarge", func(t *testing.T) {
		defer test.MockVariableValue(&setting.UI.MaxDisplayFileSize, 16)()

		// a seekable artifact is served straight from storage, so it must hit the same size limit as the buffered paths
		req := NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download/preview/raw/abc.txt", repo.FullName())
		session.MakeRequest(t, req, http.StatusRequestEntityTooLarge)
	})

	t.Run("V4Zip", func(t *testing.T) {
		zipBytes := buildArtifactZip(t, map[string]string{
			"index.html":      "<html><body><h1>v4 zip</h1></body></html>",
			"style.css":       "body{color:red}",
			"sort.js":         "document.body.dataset.sorted = 'true';",
			"logs/output.txt": "v4 log output",
		})
		overwriteArtifactStorageContent(t, 22, zipBytes)

		// /preview lists files extracted from the zip's central directory.
		req := NewRequestf(t, "GET", "/%s/actions/runs/792/artifacts/artifact-v4-download/preview", repo.FullName())
		resp := session.MakeRequest(t, req, http.StatusOK)
		body := resp.Body.String()
		assert.Contains(t, body, "index.html")
		assert.Contains(t, body, "logs/output.txt")
		assert.Contains(t, body, `/preview?path=index.html" title="index.html"`)
		assert.NotContains(t, body, "<iframe")

		req = NewRequestf(t, "GET", "/%s/actions/runs/792/artifacts/artifact-v4-download/preview/raw/index.html", repo.FullName())
		resp = session.MakeRequest(t, req, http.StatusOK)
		assert.Equal(t, "<html><body><h1>v4 zip</h1></body></html>", resp.Body.String())
		assert.Contains(t, resp.Header().Get("Content-Type"), "text/html")
		assert.Contains(t, resp.Header().Get("Content-Disposition"), "inline")
		assert.Contains(t, resp.Header().Get("Content-Security-Policy"), "sandbox")

		req = NewRequestf(t, "GET", "/%s/actions/runs/792/artifacts/artifact-v4-download/preview/raw/style.css", repo.FullName())
		resp = session.MakeRequest(t, req, http.StatusOK)
		assert.Equal(t, "body{color:red}", resp.Body.String())
		assert.Contains(t, resp.Header().Get("Content-Type"), "text/css")

		req = NewRequestf(t, "GET", "/%s/actions/runs/792/artifacts/artifact-v4-download/preview/raw/sort.js", repo.FullName())
		resp = session.MakeRequest(t, req, http.StatusOK)
		assert.Equal(t, "document.body.dataset.sorted = 'true';", resp.Body.String())
		assert.Contains(t, resp.Header().Get("Content-Type"), "javascript")

		req = NewRequestf(t, "GET", "/%s/actions/runs/792/artifacts/artifact-v4-download/preview/raw/logs/output.txt", repo.FullName())
		resp = session.MakeRequest(t, req, http.StatusOK)
		assert.Equal(t, "v4 log output", resp.Body.String())

		// Unknown path inside the zip returns 404 instead of falling back.
		req = NewRequestf(t, "GET", "/%s/actions/runs/792/artifacts/artifact-v4-download/preview/raw/missing.txt", repo.FullName())
		session.MakeRequest(t, req, http.StatusNotFound)
	})

	t.Run("DownloadV4StorageErrorIsNotAttachment", func(t *testing.T) {
		artifact := unittest.AssertExistsAndLoadBean(t, &actions_model.ActionArtifact{ID: 22})
		require.NoError(t, storage.ActionsArtifacts.Delete(artifact.StoragePath))

		// the error page must render as a page, not download as a corrupt .zip
		req := NewRequestf(t, "GET", "/%s/actions/runs/792/artifacts/artifact-v4-download", repo.FullName())
		resp := session.MakeRequest(t, req, http.StatusInternalServerError)
		assert.NotContains(t, resp.Header().Get("Content-Disposition"), "attachment")
	})

	t.Run("DownloadViewUnchanged", func(t *testing.T) {
		req := NewRequestf(t, "GET", "/%s/actions/runs/791/artifacts/artifact-download", repo.FullName())
		resp := session.MakeRequest(t, req, http.StatusOK)
		assert.Contains(t, resp.Header().Get("Content-Disposition"), "attachment; filename=artifact-download.zip")
	})
}
