name: python-setup
description: Set up uv and python and restore the uv cache

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      with:
        python-version: 3.14
        save-cache: ${{ github.workflow == 'cache-seeder' }}
