name: docker-dryrun
description: Composite action that performs the container build steps for a single platform.

inputs:
  platform:
    description: "The target platform: linux/amd64, linux/arm64, linux/riscv64."
    required: true

runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      with:
        cache-image: false
    - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
    - name: Build regular image
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
      with:
        context: .
        platforms: ${{ inputs.platform }}
        push: false
        file: Dockerfile
        cache-from: type=registry,ref=ghcr.io/go-gitea/gitea:buildcache-rootful
    - name: Build rootless image
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
      with:
        context: .
        platforms: ${{ inputs.platform }}
        push: false
        file: Dockerfile.rootless
        cache-from: type=registry,ref=ghcr.io/go-gitea/gitea:buildcache-rootless
