// Copyright 2021 The Gitea Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

// Code generated by go generate; DO NOT EDIT.
// This file was generated by generate-services.go

package routers

import (
	_ "code.gitea.io/gitea/models"
	_ "code.gitea.io/gitea/modules/auth/sso"
	_ "code.gitea.io/gitea/modules/cache"
	_ "code.gitea.io/gitea/modules/cron"
	_ "code.gitea.io/gitea/modules/eventsource"
	_ "code.gitea.io/gitea/modules/highlight"
	_ "code.gitea.io/gitea/modules/indexer/code"
	_ "code.gitea.io/gitea/modules/indexer/issues"
	_ "code.gitea.io/gitea/modules/indexer/stats"
	_ "code.gitea.io/gitea/modules/markup"
	_ "code.gitea.io/gitea/modules/markup/external"
	_ "code.gitea.io/gitea/modules/migrations"
	_ "code.gitea.io/gitea/modules/notification/action"
	_ "code.gitea.io/gitea/modules/notification/indexer"
	_ "code.gitea.io/gitea/modules/notification/mail"
	_ "code.gitea.io/gitea/modules/notification/ui"
	_ "code.gitea.io/gitea/modules/notification/webhook"
	_ "code.gitea.io/gitea/modules/setting"
	_ "code.gitea.io/gitea/modules/ssh"
	_ "code.gitea.io/gitea/modules/storage"
	_ "code.gitea.io/gitea/modules/svg"
	_ "code.gitea.io/gitea/modules/task"
	_ "code.gitea.io/gitea/services/mailer"
	_ "code.gitea.io/gitea/services/mirror"
	_ "code.gitea.io/gitea/services/pull"
	_ "code.gitea.io/gitea/services/repository"
	_ "code.gitea.io/gitea/services/webhook"
)
