apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
spec:
  ingressClassName: traefik
  rules:
    - host: gitea.guardian.fursa.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea
                port:
                  name: http
