name: cron-renovate

on:
  schedule:
    - cron: "0 1 * * 1" # every Monday at 01:00 UTC
  workflow_dispatch:

jobs:
  cron-renovate:
    runs-on: ubuntu-latest
    if: github.repository == 'go-gitea/gitea' # prevent running on forks
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: renovatebot/github-action@v46
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_PLATFORM_COMMIT: "true" # commit directly to branch to avoid API rate limits and for commit signing.
          RENOVATE_BINARY_SOURCE: install # auto-install go/node toolchains needed by post-upgrade tasks.
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '["^make (tidy|svg)$"]'
