name: "Docs: Publish"

on:
  push:
    paths:
      - "docs/**"
    branches:
      - main

jobs:
  compliance-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.1'
      - name: build docs
        run: |
          cd docs
          make trans-copy clean build
      - name: publish to netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          production-branch: main
          publish-dir: docs/public/
        env:
          NETLIFY_SITE_ID: d2260bae-7861-4c02-8646-8f6440b12672
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
