#!/bin/bash

SDATA=''; SCOMMON='';
if env | grep -q root; then
  export SDATA=$(echo $SNAP_DATA | sed s!$SNAP_REVISION!current!)
  export SCOMMON="$SNAP_COMMON"
  export isRoot=`true`
  snapctl set GITEA_WORK_DIR=$SDATA/custom
  snapctl set GITEA_CUSTOM=$SCOMMON
else
  echo "You are not running gitea as root. This is required for the snap package."
  echo "Please re-run as root."
  exit 1
fi

export appini="$SDATA/custom/conf/app.ini"

function mkDirCommon(){
  for dir in $@; do
    mkdir -p "$SCOMMON/$dir"
  done
}

function mkdirData(){
  for dir in $@; do
    mkdir -p "$SDATA/$dir"
    if [ -d $SNAP/$dir ]; then
      cp -r --preserve=mode           \
            $SNAP/$dir/*              \
            $SNAP/$dir/.[a-zA-Z0-9-]* \
            $SDATA/$dir/ 2> $SCOMMON/log/snap-mkdirData.log
    fi
  done
}

mkDirCommon pictures           \
            repositories       \
            attachments        \
            data               \
            log

mkdirData   certs              \
            sshkeytest         \
            custom/conf        \
            static/templates   \
            static/scripts     \
            static/public

if [ ! -f $appini ]; then
  echo "app.ini not found. Initializing Configuration."
  out=$(sed s!SNAP_DIR_DATA!$SDATA!g $SNAP/gitea/snapApp.ini)
  out=$(echo "$out" | sed s!SNAP_DIR_COMMON!$SCOMMON!g)
  echo "$out" > $appini
fi

# Configure Git to use the right templates
mkdir -p $SDATA/git/
cp -r --preserve=mode $SNAP/usr/share/git-core/templates $SDATA/git/
$SNAP/usr/bin/git config --global init.templateDir $SDATA/git/templates/
